<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
</head>
<body style="font-family: 'Segoe UI', Helvetica, Arial, sans-serif; -webkit-font-smoothing: antialiased; margin: 0; padding: 40px 10px; background-color: #f4f4f4;">
    
    <table role="presentation" border="0" cellpadding="0" cellspacing="0" style="width: 100%; max-width: 600px; margin: 0 auto; background-color: #ffffff; border-radius: 16px; overflow: hidden; box-shadow: 0 10px 30px rgba(0,0,0,0.05);">
        
        <tr>
            <td style="background-color: #1a1a1a; padding: 40px; text-align: center;">
                <h1 style="color: #ffffff; font-size: 22px; font-weight: bold; margin: 0; letter-spacing: 2px; text-transform: uppercase;">
                    New Inquiry
                </h1>
                <p style="color: #28a745; margin: 10px 0 0 0; font-size: 14px; letter-spacing: 1px; font-weight: bold;">
                    From your website contact form
                </p>
            </td>
        </tr>

        <tr>
            <td style="padding: 40px;">
                
                <table role="presentation" border="0" cellpadding="0" cellspacing="0" style="width: 100%;">
                    <tr>
                        <td style="padding-bottom: 25px;">
                            <p style="margin: 0 0 5px 0; color: #888888; font-size: 11px; font-weight: bold; text-transform: uppercase; letter-spacing: 1.5px;">Customer Name</p>
                            <p style="margin: 0; font-size: 16px; color: #1a1a1a; font-weight: 600;">{{ $data['name'] }}</p>
                        </td>
                    </tr>

                    <tr>
                        <td style="padding-bottom: 25px;">
                            <table role="presentation" border="0" cellpadding="0" cellspacing="0" style="width: 100%;">
                                <tr>
                                    <td style="width: 50%;">
                                        <p style="margin: 0 0 5px 0; color: #888888; font-size: 11px; font-weight: bold; text-transform: uppercase; letter-spacing: 1.5px;">Email Address</p>
                                        <p style="margin: 0; font-size: 15px; color: #1a1a1a;">
                                            <a href="mailto:{{ $data['email'] }}" style="color: #28a745; text-decoration: none; font-weight: 600;">{{ $data['email'] }}</a>
                                        </p>
                                    </td>
                                    <td style="width: 50%;">
                                        <p style="margin: 0 0 5px 0; color: #888888; font-size: 11px; font-weight: bold; text-transform: uppercase; letter-spacing: 1.5px;">Phone</p>
                                        <p style="margin: 0; font-size: 15px; color: #1a1a1a; font-weight: 600;">{{ $data['phone'] }}</p>
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>

                    <tr>
                        <td>
                            <p style="margin: 0 0 10px 0; color: #888888; font-size: 11px; font-weight: bold; text-transform: uppercase; letter-spacing: 1.5px;">Message Content</p>
                            <div style="background-color: #fcfcfc; padding: 25px; border-radius: 12px; border: 1px solid #eeeeee; color: #444444; font-size: 15px; line-height: 1.7;">
                                {!! nl2br(e($data['message'])) !!}
                            </div>
                        </td>
                    </tr>
                </table>

            </td>
        </tr>

        <tr>
            <td style="padding: 0 40px 40px 40px; text-align: center;">
                <hr style="border: 0; border-top: 1px solid #eeeeee; margin-bottom: 20px;">
                <p style="margin: 0; font-size: 12px; color: #aaaaaa;">
                    This email was automatically generated by your website's contact form.<br>
                    &copy; {{ date('Y') }} Your Cleaning Business. All rights reserved.
                </p>
            </td>
        </tr>
    </table>

</body>
</html>